// Textos da parcela R1 (dona: R1a e R1b): a página de teste da prévia (?painel=1, render/motor/bancada.js).
// registrar(registrarTextos) vem de ui/textos.js. Português do Brasil, sem travessão.
export function registrar(registrarTextos) {
  registrarTextos('r1', {
    'r1.teste.titulo': 'Página de teste',
    'r1.teste.aparelho': 'Aparelho',
    'r1.teste.perfil': 'Perfil',
    'r1.teste.sugerido': 'sugerido',
    'r1.teste.resolucao': 'Resolução',
    'r1.teste.capacidades': 'Capacidades',
    'r1.teste.limites': 'Limites',
    'r1.teste.bancada': 'Bancada',
    'r1.teste.medindo': 'Medindo {n} quadros...',
    'r1.teste.msMedio': 'ms médio',
    'r1.teste.p95': 'p95',
    'r1.teste.qps': 'qps',
    'r1.teste.gpu': 'GPU (cerca)',
    'r1.teste.gpuTimer': 'GPU (consulta)',
    'r1.teste.chamadas': 'chamadas',
    'r1.teste.triangulos': 'triângulos',
    'r1.teste.sombra': 'sombra',
    'r1.teste.programas': 'Programas',
    'r1.teste.acima': 'acima da guarda',
    'r1.teste.compilacao': 'compilação',
    'r1.teste.nenhum': 'nenhum',
    'r1.teste.medir': 'Medir de novo',
    'r1.teste.copiar': 'Copiar resultado',
    'r1.teste.copiado': 'Copiado',
    'r1.teste.semCopiar': 'Selecione e copie o texto abaixo',
    'r1.teste.cena': 'Cena {nome}',
    'r1.teste.sim': 'sim',
    'r1.teste.nao': 'não',
    // página de teste do PC do dono (PC1, D66): perfil, resolução, tempo de placa por passe, memória e aquecimento
    'r1.teste.motivo': 'motivo',
    'r1.teste.interna': 'resolução interna',
    'r1.teste.daNativa': '{pct}% da nativa ({w} x {h})',
    'r1.teste.dinamica': 'resolução dinâmica',
    'r1.teste.dinCronometro': 'pelo cronômetro da placa, alvo de {ms} ms',
    'r1.teste.dinQuadro': 'pelo tempo de quadro',
    'r1.teste.dinFixa': 'travada',
    'r1.teste.teto': 'alvo {alvo} qps, piso {piso}, teto {teto}',
    'r1.teste.passes': 'Tempo de placa por passe',
    'r1.teste.passesNota': 'ms por quadro, média de {n} quadros',
    'r1.teste.semCronometro': 'sem o cronômetro da placa neste aparelho',
    'r1.teste.total': 'total',
    'r1.teste.passe.sombra': 'sombra própria',
    'r1.teste.passe.preparo': 'sombra de longe, HAO e luz da rua',
    'r1.teste.passe.ceu': 'céu e luz do ambiente',
    'r1.teste.passe.terreno': 'terreno',
    'r1.teste.passe.agua': 'água',
    'r1.teste.passe.predios': 'prédios',
    'r1.teste.passe.colocaveis': 'serviços e Holding',
    'r1.teste.passe.arvores': 'árvores',
    'r1.teste.passe.vias': 'vias',
    'r1.teste.passe.vida': 'carros e gente',
    'r1.teste.passe.arcologia': 'Arcologia',
    'r1.teste.passe.resto': 'resto da cena',
    'r1.teste.passe.pos': 'pós e composição',
    'r1.teste.passe.outros': 'outros',
    'r1.teste.memoria': 'Memória de vídeo (estimada)',
    'r1.teste.memTexturas': 'texturas',
    'r1.teste.memAlvos': 'alvos de desenho',
    'r1.teste.memBuffers': 'geometria nos buffers',
    'r1.teste.memTela': 'tela',
    'r1.teste.memCena': 'geometria da cena',
    'r1.teste.memTeto': 'teto do perfil',
    'r1.teste.aquecimento': 'aquecimento',
    'r1.teste.aquecendo': 'aquecendo os programas...',
    'r1.teste.aquecido': '{n} programas em {ms} ms',
    'r1.teste.depois': 'compilações depois de pronto',
    'r1.teste.bloqueio': 'bloqueio',
  });
}
