// Textos da parcela S2 (dona: S2a e S2b): avisos da cidade e dos prédios, camadas Zonas, Bem-estar, Água, Energia,
// Serviços, Valor e Nível, fatores do bem-estar e da demanda, o que falta para subir de nível. Português do Brasil, sem
// travessão; taxas em "/h" (hora de jogo, D42). registrar(registrarTextos) vem de ui/textos.js.
export function registrar(registrarTextos) {
  registrarTextos('s2', {
    // alertas da cidade (q.barra().alertas, q.avisos, evento aviso)
    'aviso.faltaAgua': 'Falta água: {n} prédios sem água',
    'aviso.faltaEnergia': 'Falta energia: {n} prédios sem energia',
    'aviso.bemEstarPerto': 'Bem-estar a {delta} pontos de perder a Contribuição de 11',
    'aviso.desempregoAlto': 'Desemprego de {pct}%: faltam vagas de trabalho',
    'aviso.faltamTrabalhadores': 'Faltam {n} trabalhadores na cidade',
    'aviso.abandonoPerto': '{n} prédios perto do abandono',
    'aviso.obrasParadas': '{n} obras paradas por falta de material',
    // avisos de prédio (q.predio().avisos) que a U1a ainda não tem em cartao.aviso.*
    'aviso.abandono': 'Perto do abandono',
    'aviso.semClientes': 'Poucos clientes',
    'aviso.desemprego': 'Moradores sem emprego',
    'aviso.bemEstarBaixo': 'Bem-estar muito baixo',
    'aviso.semRede': 'A rua não leva canos nem cabos: melhore a rua para ligar à rede',
    // prévia de construir (q.construir.previa().semRede)
    'previa.semRede': 'Esta rua não tem canos nem cabos: o que for produzido aqui só chega à rede depois de melhorar a rua',
    // zonas (camada Zonas)
    'zona.nenhuma': 'Sem zona',
    'zona.resBaixa': 'Residencial baixa',
    'zona.resMedia': 'Residencial média',
    'zona.resAlta': 'Residencial alta',
    'zona.comBaixa': 'Comercial baixa',
    'zona.comAlta': 'Comercial alta',
    'zona.escritorio': 'Escritórios',
    'zona.industria': 'Indústria',
    // camadas
    'camada.zonas': 'Zonas',
    'camada.zonas.resumo': '{pintadas} células pintadas, {ocupadas} com prédio',
    'camada.bemEstar': 'Bem-estar',
    'camada.bemEstar.faixa5': 'Até 30: Contribuição de 5 por morador',
    'camada.bemEstar.faixa8': 'De 31 a 60: Contribuição de 8',
    'camada.bemEstar.faixa11': 'De 61 a 100: Contribuição de 11',
    'camada.bemEstar.resumo': 'Média da cidade {media}; Contribuição de {tarifa} por morador por hora',
    'camada.agua': 'Água',
    'camada.agua.ok': 'Com água',
    'camada.agua.racionado': 'Racionada',
    'camada.agua.sem': 'Sem água',
    'camada.agua.produtor': 'Produz água',
    'camada.agua.resumo': 'Oferta de {oferta} m³/h para uma demanda de {demanda} m³/h',
    'camada.energia': 'Energia',
    'camada.energia.ok': 'Com energia',
    'camada.energia.racionado': 'Racionada',
    'camada.energia.sem': 'Sem energia',
    'camada.energia.produtor': 'Gera energia',
    'camada.energia.resumo': 'Oferta de {oferta} kW para uma demanda de {demanda} kW; {importado} kW vêm da rodovia',
    'camada.servicos': 'Serviços',
    'camada.servicos.sem': 'Sem atendimento',
    'camada.servicos.completo': 'Bem atendido',
    'camada.servicos.resumo': 'Atendimento médio das ruas: {media}%',
    'camada.valor': 'Valor do terreno',
    'camada.valor.baixo': 'Baixo',
    'camada.valor.nivel5': '600: o nível 5 pede daqui para cima',
    'camada.valor.alto': 'Alto',
    'camada.valor.resumo': 'Serviços, comércio e a beira da água valorizam o terreno; o abandono derruba',
    'camada.nivel': 'Nível dos prédios',
    'camada.nivel.1': 'Nível 1',
    'camada.nivel.2': 'Nível 2',
    'camada.nivel.3': 'Nível 3',
    'camada.nivel.4': 'Nível 4',
    'camada.nivel.5': 'Nível 5',
    'camada.nivel.resumo': 'Prédios por nível: {n1}, {n2}, {n3}, {n4} e {n5}',
    // fatores do bem-estar (q.predio().moradia.fatores, q.cidade().fatoresBemEstar)
    'fator.base': 'Base',
    'fator.saude': 'Saúde',
    'fator.educacao': 'Educação',
    'fator.seguranca': 'Segurança',
    'fator.bombeiros': 'Bombeiros',
    'fator.lazer': 'Praça e parque',
    'fator.comercio': 'Comércio perto',
    'fator.agua': 'Sem água',
    'fator.energia': 'Sem energia',
    'fator.desemprego': 'Desemprego',
    'fator.holding': 'Holding',
    // fatores da demanda (q.demanda().fatores)
    'fator.vagas': 'Vagas de trabalho abertas',
    'fator.vazias': 'Imóveis vazios',
    'fator.bemEstar': 'Bem-estar da cidade',
    'fator.impulso': 'Cidade nova atrai gente',
    'fator.atratividade': 'Atratividade',
    'fator.parte': 'Fatia desta zona (%)',
    'fator.decisao': 'Decisões do Conselho',
    'fator.consumo': 'Compras que a cidade quer fazer',
    'fator.maoDeObra': 'Gente sem emprego',
    'fator.bens': 'Mercadoria que o comércio pede',
    'fator.rodovia': 'Sem ligação com a rodovia',
    'fator.superior': 'Gente com superior sem emprego',
    'fator.ocupacao': 'Vagas ocupadas',
    'fator.clientes': 'Clientes',
    // o que falta para subir de nível (q.predio().nivelProx.falta)
    'falta.agua': 'Água',
    'falta.energia': 'Energia',
    'falta.saude': 'Saúde na rua do prédio',
    'falta.educacao': 'Educação na rua do prédio',
    'falta.seguranca': 'Segurança na rua do prédio',
    'falta.bombeiros': 'Bombeiros na rua do prédio',
    'falta.lazer': 'Praça ou parque perto',
    'falta.valor': 'Valor do terreno acima de 600',
    'falta.bemEstar': 'Bem-estar acima de 70',
    'falta.ocupacao': 'Nove em cada dez vagas ocupadas',
    'falta.maximo': 'Já está no nível 5',
    // cidade
    'cidade.redes.ligacao': 'Energia da rodovia: até 5 MW, {usado} kW em uso',
    'cidade.redes.semLigacao': 'Ligue uma avenida ao nó de entrada da rodovia para receber energia',
  });
}
