// Textos da U1a e da U1b (pele, HUD, seleção e gestão): primitivas, barra de cima, calendário (D67), cartão e folha do
// selecionado, faixa de alerta, avisos, objetivos, menu, menu de contexto, telas Economia, Holding, Cidade, Progresso,
// Conselho, a decisão e os momentos. Português do Brasil, sem travessão; taxas só em "/h" de jogo; a receita dos
// moradores é a Contribuição (D42); dinheiro em dólar vem pronto de ui/formato.js (D87), nunca escrito aqui.
import { MES, ANO, MINUTO, HORA } from '../../comum/relogio.js';

export function registrar(registrarTextos) {
  registrarTextos('u1', {
    // primitivas
    'comp.menos': 'Menos',
    'comp.mais': 'Mais',
    'comp.minimo': 'Mínimo: {n}',
    'comp.maximo': 'Máximo: {n}',
    'comp.toqueDeNovo': 'Toque de novo para confirmar',
    'comp.voltar': 'Voltar',
    'comp.localizar': 'Localizar',
    'comp.fechar': 'Fechar',
    'comp.ligado': 'ligado',
    'comp.desligado': 'desligado',
    'comp.ordenar': 'Ordenar por {col}',
    'comp.mostrarMais': 'Mostrar mais {n}',
    'comp.verTabela': 'Ver tabela',
    'comp.verGrafico': 'Ver gráfico',
    'comp.grafico.quando': 'Quando',
    'comp.grafico.semDado': 'sem dado',

    // barra de cima
    'barra.holding': 'Holding',
    'barra.holding.nome': 'Nome',
    'barra.holding.padrao': 'Held',
    'barra.holding.nota': 'O valor da Holding soma o que ela tem e desconta a dívida.',
    'barra.marco.rotulo': 'Marco {n}: {nome}',
    'barra.marco.titulo': 'Marco {n} · {nome}',
    'barra.marco.xp': 'Pontos até o próximo marco',
    'barra.marco.deXp': '{xp} de {prox} XP',
    'barra.marco.faltam': 'Faltam {n} XP para o marco {prox}.',
    'barra.marco.ultimo': 'Último marco desta versão.',
    'barra.marco.requisito.torre.e4': 'Pede também a Blade Tower pronta.',
    'barra.creditos.rotulo': 'Caixa: {valor}; saldo {saldo}',
    'barra.pop.rotulo': 'População: {valor}; {hora}',
    'barra.pop.titulo': 'População',
    'barra.pop.moradores': 'Moradores',
    'barra.pop.ritmo': 'Novos moradores',
    'barra.bem.rotulo': 'Bem-estar {n}; {margem}',
    'barra.bem.rotuloVazia': 'Bem-estar; {margem}',
    'barra.bem.nome': 'Bem-estar',
    'barra.bem.titulo': 'Bem-estar {n}',
    'barra.bem.acima': '+{n} acima de {degrau}',
    'barra.bem.faltam': 'faltam {n} para {degrau}',
    'barra.bem.topo': 'faixa mais alta',
    'barra.bem.semMoradores': 'sem moradores',
    'barra.bem.paga': 'Cada morador contribui com {tarifa} por hora de jogo.',
    'barra.bem.pagaVazia': 'Ainda sem moradores. A contribuição começa com os primeiros, pela faixa do bem-estar:',
    'barra.bem.cai': 'Abaixo de {degrau}, cai para {tarifa}.',
    'barra.bem.faixas': 'Faixas da contribuição',
    'barra.bem.ate': 'até {ate}',
    'barra.bem.deAte': '{de} a {ate}',
    'barra.bem.tarifa': '{tarifa} por morador',
    'barra.bem.media': 'Média dos prédios da cidade, suavizada em 1 mês e arredondada antes da faixa.',
    'barra.demanda.rotulo': 'Demanda: residencial {r}, comercial {c}, indústria {i}',
    'barra.demanda.titulo': 'Demanda',
    'barra.demanda.R': 'Residencial',
    'barra.demanda.C': 'Comercial',
    'barra.demanda.I': 'Indústria',
    'barra.demanda.E': 'Escritórios',
    'barra.demanda.nota': 'De 0 a 100: quanto a cidade quer de cada zona agora.',
    'barra.valuation': 'Valor da Holding',
    'barra.divida': 'Dívida',
    'barra.caixa': 'Caixa',
    'barra.tela.holding': 'Holding',
    'barra.tela.economia': 'Economia',
    'barra.tela.cidade': 'Cidade',
    'barra.tela.progresso': 'Progresso',
    'barra.tela.conselho': 'Conselho',
    'barra.ver.progresso': 'Ver marcos',
    'barra.ver.cidade': 'Ver a cidade',
    'barra.conselho': 'Conselho: decisões pendentes, {n}',
    'barra.conselho.pendentes': 'Decisões pendentes',
    'barra.menu': 'Menu',
    'barra.data.mes': 'Mês do ano',
    'barra.data.mesDe': '{mes} de 12',
    'barra.data.anoNovo': '{ano} começa em',
    'barra.data.escala': `Um mês do calendário dura ${MES / MINUTO} min de jogo; um ano, ${ANO / HORA} h.`,
    'barra.data.emprestimo': 'O ano rege o limite do empréstimo.',

    // cartão do selecionado
    'cartao.servico': 'Serviço',
    'cartao.servico.agua': 'Água',
    'cartao.servico.esgoto': 'Esgoto',
    'cartao.servico.energia': 'Energia',
    'cartao.servico.saude': 'Saúde',
    'cartao.servico.educacao': 'Educação',
    'cartao.servico.seguranca': 'Segurança',
    'cartao.servico.policia': 'Segurança',
    'cartao.servico.bombeiros': 'Bombeiros',
    'cartao.servico.lazer': 'Lazer',
    'cartao.servico.praca': 'Praça',
    'cartao.servico.parque': 'Parque',
    'cartao.sub.alcance': '{tipo} · alcance de {m} m',
    'cartao.sub.nivel': '{tipo} · nível {nivel} de 5',
    'cartao.holding': 'Prédio da Holding',
    'cartao.predio': 'Prédio',
    'cartao.moradores': 'Moradores',
    'cartao.bemEstar': 'Bem-estar',
    'cartao.contribuicao': 'Contribuição',
    'cartao.atendidos': 'Atendidos',
    'cartao.eficiencia': 'Eficiência',
    'cartao.manutencao': 'Manutenção',
    'cartao.trabalhadores': 'Trabalhadores',
    'cartao.produtividade': 'Produtividade',
    'cartao.nivel': 'Nível',
    'cartao.linhas': 'Linhas ativas',
    'cartao.deN': '{a} de {b}',
    'cartao.aviso.semAgua': 'Sem água',
    'cartao.aviso.semEsgoto': 'Sem esgoto',
    'cartao.aviso.semEnergia': 'Sem energia',
    'cartao.aviso.semAcesso': 'Sem acesso à rua',
    'cartao.aviso.abandonado': 'Abandonado',
    'cartao.aviso.semMaterial': 'Obra parada: falta material',
    'cartao.aviso.semTrabalhadores': 'Faltam trabalhadores',
    'cartao.aviso.racionado': 'Água ou energia racionada',
    'cartao.aviso.grave': 'Problema grave neste prédio',
    'cartao.aviso.atencao': 'Este prédio precisa de atenção',
    'cartao.aviso.info': 'Aviso sobre este prédio',
    'cartao.aviso.holding': 'Aviso da Holding',
    'cartao.desde': 'há {n} min de jogo',
    'cartao.obra': 'Em obra: {fase}',
    'cartao.obra.canteiro': 'canteiro',
    'cartao.obra.fundacao': 'fundação',
    'cartao.obra.estrutura': 'estrutura',
    'cartao.obra.fechamento': 'fechamento',
    'cartao.detalhes': 'Detalhes',

    // tela Economia
    'eco.titulo': 'Economia',
    'eco.aba.orcamento': 'Orçamento',
    'eco.aba.emprestimo': 'Empréstimo',
    'eco.semDados': 'Os números da economia aparecem quando a partida começa.',
    'eco.saldoHora': 'Saldo por hora',
    'eco.dicaHora': 'O que é hora de jogo',
    'eco.conta': 'Receitas {rec} e despesas {des}',
    'eco.caixa': 'Caixa',
    'eco.divida': 'Dívida',
    'eco.valuation': 'Valor da Holding',
    'eco.graficoCaixa': 'Caixa nos últimos 12 meses',
    'eco.graficoFluxo': 'Receitas e despesas por hora',
    'eco.receitasCurto': 'Receitas',
    'eco.despesasCurto': 'Despesas',
    'eco.receitas': 'Receitas por hora',
    'eco.despesas': 'Despesas por hora',
    'eco.rec.moradores': 'Contribuição dos moradores',
    'eco.rec.cidade': 'Material vendido à cidade',
    'eco.rec.deposito': 'Vendas no Depósito',
    'eco.rec.marcos': 'Prêmios de marco',
    'eco.des.servicos': 'Manutenção dos serviços',
    'eco.des.vias': 'Manutenção das vias',
    'eco.des.ligacao': 'Energia de fora',
    'eco.des.salarios': 'Salários da Holding',
    'eco.des.juros': 'Juros do empréstimo',
    'eco.des.importacao': 'Material importado pela Holding',
    'eco.des.importacaoCidade': 'Importação para a cidade',
    'eco.regra': 'Contribuição: {pop} × {tarifa} = {total}',
    'eco.regraMedia': 'Média de {media} por morador: {total}',
    'eco.regraFaixa': 'Bem-estar {bem}: a faixa de {de} a {ate} paga {tarifa} por morador por hora',
    'eco.naoPago': 'Sem pagar nesta hora',
    'eco.naoPago.servicos': 'Serviços',
    'eco.naoPago.servicos.efeito': 'trabalham só na fração paga',
    'eco.naoPago.salarios': 'Salários da Holding',
    'eco.naoPago.salarios.efeito': 'linhas da Holding e obras da Arcologia param',
    'eco.tudoPago': 'Tudo pago nesta hora.',
    'eco.caixaNunca': 'O caixa nunca fica abaixo de zero: o que não dá para pagar não vira dívida.',
    'eco.livia': 'Lívia Andrade, diretora financeira',
    'eco.livia.fala': 'As regras do empréstimo valem para a partida inteira. Use nos primeiros anos e quite cedo.',
    'eco.livia.ano': 'O limite deste ano acabou. Em {ano} ele volta inteiro.',
    'eco.regras': 'Regras do empréstimo Lombard',
    'eco.regra.porAno': 'Até {n} por ano do calendário',
    'eco.regra.taxa': 'Juros de {pct}% ao ano sobre o saldo de cada contrato',
    'eco.regra.divida': 'Dívida total até {n}, contando os juros devidos',
    'eco.fundo': 'Fundo de teste',
    'eco.fundo.saldo': 'Saldo: {saldo} de {total}. Saque a qualquer hora, o valor que quiser, para pagar as construções.',
    'eco.fundo.valor': 'Valor a sacar',
    'eco.fundo.sacarN': 'Sacar {n}',
    'eco.fundo.tudo': 'Sacar tudo',
    'eco.fundo.sacou': 'Sacou {n} do fundo.',
    'eco.fundo.vazio': 'O fundo de teste está vazio.',
    'eco.regra.lombard': 'Crédito Lombard, com os ativos da Holding em garantia: renova a cada {anos} anos enquanto a dívida couber em {pct}% dos ativos; sem cobertura, juros de {mora}% ao ano',
    'eco.regra.prazo': 'Prazo de {anos} anos; depois, juros de {mora}% ao ano',
    'eco.regra.passo': 'Tomado em múltiplos de {n}',
    'eco.disponivel': 'Disponível em {ano}',
    'eco.deN': '{a} de {b}',
    'eco.tomar': 'Tomar empréstimo',
    'eco.valorTomar': 'Valor a tomar',
    'eco.tomarN': 'Tomar {n}',
    'eco.tomado': '{n} entrou no caixa.',
    'eco.bloqueio.ano': 'O limite deste ano acabou. Ele volta em {ano}.',
    'eco.bloqueio.divida': 'A dívida chegou ao máximo permitido.',
    'eco.contratos': 'Contratos',
    'eco.col.ano': 'Ano',
    'eco.col.valor': 'Valor',
    'eco.col.saldo': 'Saldo',
    'eco.col.vence': 'Vence',
    'eco.col.juros': 'Juros',
    'eco.pagarJuros': 'Pagar juros ({n})',
    'eco.semJuros': 'Não há juros a pagar agora.',
    'eco.pagarParcela': 'Pagar parcela',
    'eco.parcelaDica': 'Juros mais 10% do principal, no mínimo {min}, dos contratos mais antigos primeiro.',
    'eco.quitar': 'Quitar tudo ({n})',
    'eco.pago': 'Pagamento feito.',
    'eco.quitado': 'Dívida quitada.',
    'eco.semDivida': 'Sem dívida. O empréstimo fica à mão quando precisar.',

    // ---------------------------------------------------------------- U1b
    // calendário (D67) e unidades curtas do dinheiro (D87)
    'cal.data': '{mes} {ano}',
    'cal.mes.1': 'jan.', 'cal.mes.2': 'fev.', 'cal.mes.3': 'mar.', 'cal.mes.4': 'abr.', 'cal.mes.5': 'mai.', 'cal.mes.6': 'jun.',
    'cal.mes.7': 'jul.', 'cal.mes.8': 'ago.', 'cal.mes.9': 'set.', 'cal.mes.10': 'out.', 'cal.mes.11': 'nov.', 'cal.mes.12': 'dez.',
    'unid.mil': 'mil',
    'unid.tri': 'tri',
    'tela.carregando': 'Abrindo...',
    'tela.erro': 'Não foi possível abrir esta tela. Feche e tente de novo.',

    // trilho e faixa de alerta
    'trilho.rotulo': 'Vista',
    'trilho.camadas': 'Camadas',
    'trilho.mural': 'Mural',
    'trilho.foto': 'Modo foto',
    'faixa.acao.ver': 'Ver',
    'faixa.acao.verCamada': 'Ver camada',
    'faixa.acao.emprestimo': 'Empréstimo',
    'faixa.acao.deposito': 'Depósito',
    'faixa.acao.orcamento': 'Orçamento',
    'faixa.mais': 'Mais {n} alertas',
    'faixa.outros': 'Outros alertas',
    'faixa.saidas': 'Outras saídas',
    'faixa.maisCurto': 'Mais',
    'faixa.generico.grave': 'Problema grave na cidade',
    'faixa.generico.atencao': 'A cidade pede atenção',
    'faixa.generico.info': 'Aviso da cidade',
    'aviso.u1b.objetivo': 'Objetivo cumprido: {texto}',
    'aviso.u1b.ladrilho': 'Área nova da Holding liberada para construir.',
    'aviso.u1b.atrasada': 'O cálculo do trânsito atrasou; o tempo esperou por ele.',

    // objetivos (D58)
    'obj.chip': 'Objetivos',
    'obj.abrir': 'Objetivos abertos: {n}. Mostrar',
    'obj.recolher': 'Recolher os objetivos',
    'obj.listar': 'Ver os três objetivos',
    'obj.titulo': 'Objetivos abertos',
    'obj.rotulo': 'Objetivo {i} de {n} · {dominio}',
    'obj.dominio.cidade': 'Cidade',
    'obj.dominio.holding': 'Holding',
    'obj.dominio.arcologia': 'Arcologia',
    'obj.generico.cidade': 'Faça a cidade crescer',
    'obj.generico.holding': 'Faça a Holding produzir',
    'obj.generico.arcologia': 'Leve a Arcologia adiante',
    'obj.conta': '{feito} de {total}',
    'obj.ir': 'Ir',
    'obj.irPara': 'Ir: {texto}',
    'obj.nota': 'Sempre há um objetivo da cidade, um da Holding e um da Arcologia.',
    'obj.holding': 'Holding Held',

    // "Onde você parou"
    'retomar.titulo': 'Onde você parou',
    'retomar.desde': 'salvo em {data}',
    'retomar.continuar': 'Continuar',

    // menu
    'menu.titulo': 'Menu',
    'menu.retomar': 'Retomar',
    'menu.salvar': 'Salvar agora',
    'menu.salvo': 'Partida salva.',
    'menu.naoSalvo': 'Não foi possível salvar agora.',
    'menu.ajuda': 'Ajuda',
    'menu.sair': 'Sair para o menu inicial',
    'menu.tela.carregar': 'Carregar',
    'menu.tela.holding': 'Holding',
    'menu.tela.economia': 'Economia',
    'menu.tela.cidade': 'Cidade',
    'menu.tela.progresso': 'Progresso',
    'menu.tela.conselho': 'Conselho',
    'menu.tela.arcologia': 'Livro da Arcologia',
    'menu.tela.camadas': 'Camadas',
    'menu.tela.mural': 'Mural',
    'menu.tela.configuracoes': 'Configurações',
    'menu.glossario': 'Glossário',
    'menu.atalhos': 'Atalhos do teclado',
    'menu.g.demanda': 'Demanda:',
    'menu.g.demanda.def': 'de 0 a 100, quanto a cidade quer de cada zona agora. Zona com demanda alta enche primeiro.',
    'menu.g.bemEstar': 'Bem-estar:',
    'menu.g.bemEstar.def': 'média dos prédios residenciais. Até 30 cada morador contribui com a faixa de baixo; de 31 a 60, com a do meio; de 61 em diante, com a de cima.',
    'menu.g.marco': 'Marco:',
    'menu.g.marco.def': 'degrau da cidade pelo XP (moradores, bem-estar, obras). Cada marco traz prêmio, áreas e o que pode ser construído.',
    'menu.g.lote': 'Lote:',
    'menu.g.lote.def': 'cada linha da Holding produz de 1 a 10 unidades por ordem. Lote de 10 leva 8 vezes o tempo de 1.',
    'menu.g.deposito': 'Depósito:',
    'menu.g.deposito.def': 'vende o estoque a 150% do preço base, até 100 vendas a cada 4 h de jogo.',
    'menu.g.medidores': 'Influência e Legado:',
    'menu.g.medidores.def': 'de 0 a 100, movidos pelas decisões. Influência barateia áreas novas; Legado deixa a cidade mais atraente.',
    'menu.g.hora': 'Hora de jogo:',
    'menu.g.hora.def': '1 h real em 1x e 6 meses do calendário. Toda taxa "/h" é por hora de jogo.',
    'menu.a.espaco': 'Espaço',
    'menu.a.espaco.def': 'pausa e volta',
    'menu.a.velocidades': '1, 2, 3',
    'menu.a.velocidades.def': 'velocidade 1x, 2x e 4x',
    'menu.a.telas': 'Shift mais 1 a 6',
    'menu.a.telas.def': 'Holding, Economia, Cidade, Progresso e Conselho',
    'menu.a.construir': 'V, Z, X, G, H, M, B',
    'menu.a.construir.def': 'Vias, Zonas, Serviços, Lazer, Empresas, Arcologia e Demolir',
    'menu.a.camera': 'W, A, S, D, Q, E, R, F',
    'menu.a.camera.def': 'mover, girar e inclinar a câmera',
    'menu.a.esc': 'Esc',
    'menu.a.esc.def': 'fecha o que estiver aberto; sem nada aberto, abre este menu',

    // menu de contexto
    'ctx.rotulo': 'Ações rápidas',
    'ctx.detalhes': 'Detalhes',
    'ctx.localizar': 'Localizar',
    'ctx.cor': 'Cor',
    'ctx.demolir': 'Demolir',
    'ctx.producao': 'Produção',
    'ctx.melhorar': 'Melhorar',
    'ctx.zonear': 'Zonear aqui',
    'ctx.construir': 'Construir aqui',
    'ctx.valor': 'Valor do terreno',

    // cartão da via e ações dos avisos (o código vem de q.predio().avisos[].acao)
    'cartao.via': 'Via',
    'cartao.via.comprimento': 'Comprimento',
    'cartao.via.declive': 'Declive',
    'cartao.via.fluxo': 'Velocidade do trânsito',
    'cartao.via.m': '{m} m',
    'cartao.via.mao': 'Mão única',
    'cartao.via.rodovia': 'Rodovia estadual, liga Heldópolis ao país',
    'acao.verCamadaAgua': 'Ver camada de água',
    'acao.verCamadaEnergia': 'Ver camada de energia',
    'acao.verCamadaBemEstar': 'Ver camada de bem-estar',
    'acao.verCamadaEmpregos': 'Ver camada de empregos',
    'acao.construirVia': 'Construir via',
    'acao.demolir': 'Demolir',

    // folha do selecionado
    'folha.aba.geral': 'Visão geral',
    'folha.aba.moradores': 'Moradores',
    'folha.aba.servicos': 'Serviços',
    'folha.aba.trabalho': 'Trabalho',
    'folha.aba.producao': 'Produção',
    'folha.aba.predio': 'Prédio',
    'folha.avisos': 'Avisos',
    'folha.resumo': 'Resumo',
    'folha.nivel': 'Nível',
    'folha.nivelDe': 'nível {n} de 5',
    'folha.nivelMax': 'Já está no nível mais alto.',
    'folha.nivelFalta': 'Para subir falta: {lista}.',
    'folha.nivelPontos': '{pontos} de {meta} pontos para o próximo nível.',
    'folha.servicos': 'Serviços na rua do prédio',
    'folha.rede.agua': 'Água',
    'folha.rede.energia': 'Energia',
    'folha.rede.esgoto': 'Esgoto',
    'folha.obra': 'Obra',
    'folha.obraSemMaterial': 'Parada por falta de material: a Holding precisa ter estoque ou importar.',
    'folha.lares': 'Lares',
    'folha.tarifa': 'Faixa da Contribuição',
    'folha.porMorador': '{v} por morador',
    'folha.fatoresBem': 'De onde vem o bem-estar',
    'folha.fatoresProd': 'De onde vem a produtividade',
    'folha.escolaridade': 'Escolaridade',
    'folha.estudo.0': 'Básico',
    'folha.estudo.1': 'Fundamental',
    'folha.estudo.2': 'Médio',
    'folha.estudo.3': 'Superior',
    'folha.clientes': 'Clientes',
    'folha.vagas': 'Vagas por escolaridade',
    'folha.faz': 'O que faz',
    'folha.inspirado': 'Inspirado em {ref}',
    'folha.verCamada': 'Ver camada',
    'folha.emUso': 'Em uso',
    'folha.alcance': 'Alcance',
    'folha.eficienciaBaixa': 'Eficiência baixa: faltam trabalhadores ou o caixa não pagou a manutenção inteira.',
    'folha.cor': 'Cor',
    'folha.corN': 'Cor {n}',
    'folha.corPadrao': 'Cor do bairro',
    'folha.demolir': 'Demolir',
    'folha.melhorar': 'Melhorar',
    'folha.zonear': 'Zonear',
    'folha.construir': 'Construir',
    'folha.renomear': 'Renomear',
    'folha.nome': 'Nome do prédio',
    'folha.nome.ok': 'Salvar o nome',
    'folha.terreno': 'Terreno',
    'folha.arcologia': 'Arcologia de Held',
    'folha.terreno.area': 'Área',
    'folha.terreno.ladrilho': 'Licença',
    'folha.terreno.daHolding': 'da Holding',
    'folha.terreno.compravel': 'comprável por {preco}',
    'folha.terreno.trancado': 'ainda trancada',
    'folha.terreno.valor': 'Valor do terreno',
    'folha.terreno.valorDe': '{v} de 1.000',
    'folha.terreno.cota': 'Cota',
    'folha.terreno.recursos': 'Recursos naturais',
    'folha.terreno.nota': 'Zonas e serviços pedem uma via com calçada na frente.',
    'folha.recurso.rocha': 'Rocha',
    'folha.recurso.areia': 'Areia',
    'folha.recurso.argila': 'Argila',
    'folha.recurso.calcario': 'Calcário',
    'folha.recurso.fertil': 'Solo fértil',
    'folha.recurso.subterranea': 'Água subterrânea',
    'folha.via.tipo': 'Tipo',
    'folha.via.mao': 'Sentido',
    'folha.via.unica': 'mão única',
    'folha.via.dupla': 'mão dupla',
    'folha.via.devolve': 'Volta ao demolir',
    'folha.via.melhorias': 'Pode virar',
    'folha.via.largura': '{m} m de largura',
    'folha.via.rodovia': 'A rodovia é do país: não se demole nem se melhora.',
    'folha.via.arcologia': 'Via interna da Arcologia: não se demole.',
    'folha.linha': 'Linha {n} · {item}',
    'folha.linha.itemRot': 'O que esta linha faz',
    'folha.linha.lote': 'Lote',
    'folha.linha.auto': 'Auto',
    'folha.linha.progresso': 'Progresso do lote',
    'folha.linha.em1x': 'em 1x',
    'folha.linha.parada': 'Linha parada',
    'folha.linha.parar': 'Parar',
    'folha.linha.sugestao': 'Sugestão: lote de {n}',
    'folha.linha.sugestaoRot': 'Usar lote de {n}',
    'folha.linha.extrai': 'Tira {item} direto da natureza, sem insumo.',
    'folha.linha.produto': 'para {item}',
    'folha.linha.verFornecedor': 'Ver {nome}',
    'folha.linha.semFornecedor': 'sem fornecedor',
    'folha.linha.importado': 'importado',
    'folha.tempo': 'Comprar tempo',
    'folha.tempoMin': '{min} min',
    'folha.tempoRot': 'Adiantar {min} min de jogo por {preco}',
    'folha.semLinhas': 'Este prédio guarda o estoque e não tem linha de produção.',
    'folha.nivelHolding': 'nível {n} de {max}',
    'folha.nivelPede': 'O próximo nível custa {custo} e {materiais}; abre no marco {marco}.',
    'folha.nivelMaxHolding': 'Já está no nível mais alto.',
    'folha.subirNivel': 'Subir para o nível {n}',
    'folha.distArmazem': 'Distância ao armazém',

    // tela Holding
    'hold.titulo': 'Holding',
    'hold.aba.geral': 'Visão geral',
    'hold.aba.producao': 'Produção',
    'hold.aba.mercado': 'Mercado',
    'hold.aba.imoveis': 'Imóveis',
    'hold.valor': 'Valor da Holding',
    'hold.quem': '{nome}, de {jogador}, o criador',
    'hold.jogador': 'Diogo Holanda',
    'hold.lucro': 'Lucro por hora',
    'hold.medidores': 'Influência e Legado',
    'hold.influencia': 'Influência',
    'hold.legado': 'Legado',
    'hold.influencia.efeito': 'Áreas novas {pct}% mais baratas',
    'hold.legado.efeito': '+{v} de atratividade para morar',
    'hold.medidores.nota': 'As decisões do Conselho movem os dois. A Blade Tower pronta soma Legado.',
    'hold.semDados': 'Os números da Holding aparecem quando a partida começa.',
    'hold.itens': 'Materiais',
    'hold.col.item': 'Item',
    'hold.col.estoque': 'Estoque',
    'hold.col.produz': 'Produz',
    'hold.col.consome': 'Consome',
    'hold.col.cidade': 'Cidade pede',
    'hold.cidadeNota': 'A cidade compra da Holding a 100% do preço base; do marco 3 em diante, as obras de nível 3 a 5 compram só dela.',
    'hold.semItens': 'Nenhum material ainda. Abra a Pedreira e o Areal.',
    'hold.logistica': 'Frota e armazém',
    'hold.frota': 'Caminhões',
    'hold.fila': 'Na fila',
    'hold.armazem': 'Armazém',
    'hold.atraso': 'Espera média de {t} por caminhão.',
    'hold.linhas': 'Linhas de produção',
    'hold.nivel': 'nível {n}',
    'hold.semItem': 'Sem ordem',
    'hold.semPredios': 'A Holding ainda não tem prédios. Comece pelo Escritório de Obra.',
    'hold.deposito': 'Depósito',
    'hold.janela': '{a} de {b} vendas nesta janela',
    'hold.semLimite': 'Sem limite de vendas no Depósito ({n} nesta janela)',
    'hold.renova': 'Renova em {t}',
    'hold.regraDeposito': 'Venda a 150% do preço base; sem limite de vendas. Importar custa 160%.',
    'hold.abastecer': 'Abastecer a cidade',
    'hold.abastecerRot': 'Abastecer a cidade por importação',
    'hold.abastecerNota': 'Sem estoque, a Holding importa a 160% e vende à cidade a 100%: a obra não espera, e a perda aparece na Economia como importação para a cidade.',
    'hold.estoqueN': 'estoque {n}',
    'hold.venda': 'venda {v}',
    'hold.importa': 'importação {v}',
    'hold.quantidade': 'Quantidade',
    'hold.vender': 'Vender {n}',
    'hold.importar': 'Importar {n}',
    'hold.vendido': '{n} de {item} vendidos por {v}.',
    'hold.importado': '{n} de {item} a caminho.',
    'hold.vendeCidade': 'Vende à cidade',
    'hold.imoveis': 'Prédios da Holding',
    'hold.imovelSub': 'nível {n} · {a} de {b} linhas ativas',

    // tela Cidade
    'cid.titulo': 'Cidade',
    'cid.aba.geral': 'Visão geral',
    'cid.aba.demanda': 'Demanda',
    'cid.aba.bemEstar': 'Bem-estar',
    'cid.aba.servicos': 'Serviços',
    'cid.semDados': 'Os números da cidade aparecem quando os primeiros moradores chegam.',
    'cid.populacao': 'População',
    'cid.lares': 'Lares',
    'cid.novos': 'Novos moradores',
    'cid.empregos': 'Empregos',
    'cid.vagas': 'Vagas ocupadas',
    'cid.desemprego': 'Desemprego',
    'cid.trabalhadores': 'Trabalhadores',
    'cid.predios': 'Prédios',
    'cid.prediosTotal': 'Prédios da cidade',
    'cid.emObra': 'Em obra',
    'cid.abandonados': 'Abandonados',
    'cid.porNivel': 'Por nível, do 1 ao 5',
    'cid.demanda': 'Demanda por zona',
    'cid.fatoresDe': 'De onde vem: {zona}',
    'cid.semFatores': 'Os fatores aparecem quando a cidade tem moradores.',
    'cid.bemMedia': 'Bem-estar médio',
    'cid.fatoresBem': 'De onde vem o bem-estar da cidade',
    'cid.redes': 'Redes',
    'cid.redeUso': '{d} de {o}',
    'cid.ligacao': 'Energia da rodovia: {usado} de {teto} kW em uso.',
    'cid.semLigacao': 'Ligue uma avenida ao nó de entrada da rodovia para receber energia de fora.',
    'cid.servicos': 'Serviços',
    'cid.servicoSub': '{uso} de {cap} atendidos · eficiência {efic} · {manut}',
    'cid.semServicos': 'Nenhum serviço ainda. A barra de construção tem os de água, energia e saúde.',

    // tela Progresso
    'prog.titulo': 'Progresso',
    'prog.aba.marcos': 'Marcos',
    'prog.aba.areas': 'Áreas',
    'prog.aba.arcologia': 'Arcologia',
    'prog.semDados': 'Os marcos aparecem quando a partida começa.',
    'prog.marco': 'Marco {n} · {nome}',
    'prog.xp': '{xp} XP',
    'prog.premio': 'Prêmio de {v}',
    'prog.premioLicenca': 'Prêmio de {v} e {n} licença de área',
    'prog.requisito': 'Pede uma etapa da Arcologia pronta',
    'prog.areasHolding': 'Áreas da Holding',
    'prog.compraveis': 'Compráveis',
    'prog.licencas': 'Licenças',
    'prog.areaPreco': 'A próxima área custa a partir de {v}.',
    'prog.areasNota': 'Cada marco a partir do 2 traz uma licença; a área precisa encostar numa da Holding.',
    'prog.comprar': 'Comprar áreas',
    'prog.arcoTotal': 'Arcologia de Held',
    'prog.arcoTotalN': '{p} do megaprojeto',
    'prog.etapa.0': 'trancada',
    'prog.etapa.1': 'pode começar',
    'prog.etapa.2': 'em obra',
    'prog.etapa.3': 'pronta',
    'prog.semArcologia': 'As etapas aparecem quando o plano da Arcologia estiver no mapa.',
    'prog.livro': 'Abrir o Livro da Arcologia',
    'libera.acao.deposito': 'Depósito',
    'libera.acao.emprestimo': 'Empréstimo',
    'libera.regra.dependencia': 'Obras de nível 3 a 5 compram da Holding',
    'libera.nivel.armazem2': 'Armazém nível 2',
    'libera.arcologia.faseInicial': 'Arcologia inaugurada em fase inicial',

    // tela Conselho e a decisão
    'cons.titulo': 'Conselho',
    'cons.aba.decisoes': 'Decisões',
    'cons.aba.historico': 'Histórico',
    'cons.aba.conselheiros': 'Conselheiros',
    'cons.semPendentes': 'Nenhuma decisão esperando o Conselho.',
    'cons.semHistorico': 'Nenhuma decisão tomada ainda.',
    'cons.decisao': 'Decisão',
    'cons.prazo': 'Prazo: {t}',
    'cons.decidir': 'Decidir',
    'cons.porPrazo': 'valeu o padrão quando o prazo acabou',
    'cons.nota': 'Cada conselheiro propõe pelo que cuida; a escolha fica no Histórico e as falas seguem no Mural.',
    'dec.sobre': 'Conselho · decisão',
    'dec.propoe': '{quem} propõe',
    'dec.escolher': 'Escolher',
    'dec.escolherOpcao': 'Escolher: {opcao}',
    'dec.custa': 'Custa {v} agora',
    'dec.depois': 'Decidir depois',
    'dec.depoisPrazo': 'Decidir depois (prazo {t})',
    'dec.adiar': 'Pedir mais prazo',
    'dec.padrao': 'Sem escolha até o prazo, vale: {opcao}.',
    'dec.feita': 'Decidido: {opcao}.',

    // momentos (marco e etapa)
    'mom.marco': 'Marco {n}',
    'mom.etapa': 'Etapa {n} de {de} · {nome}',
    'mom.premio': 'Prêmio de {v}',
    'mom.licenca': '{n} licença de área',
    'mom.licencas': '{n} licenças de área',
    'mom.liberado': 'Liberado agora',
    'mom.continuar': 'Continuar',
  });
}
