// Textos da U1a (pele da interface): primitivas, barra de cima, cartão do selecionado e tela Economia. Português do
// Brasil, sem travessão; taxas só em "/h" de jogo e a receita dos moradores é a Contribuição (D42).
import { MES, ANO, MINUTO, HORA } from '../../comum/relogio.js';

export function registrar(registrarTextos) {
  registrarTextos('u1', {
    // primitivas
    'comp.menos': 'Menos',
    'comp.mais': 'Mais',
    'comp.minimo': 'Mínimo: {n}',
    'comp.maximo': 'Máximo: {n}',
    'comp.toqueDeNovo': 'Toque de novo para confirmar',
    'comp.voltar': 'Voltar',
    'comp.localizar': 'Localizar',
    'comp.fechar': 'Fechar',
    'comp.ligado': 'ligado',
    'comp.desligado': 'desligado',
    'comp.ordenar': 'Ordenar por {col}',
    'comp.mostrarMais': 'Mostrar mais {n}',
    'comp.verTabela': 'Ver tabela',
    'comp.verGrafico': 'Ver gráfico',
    'comp.grafico.quando': 'Quando',
    'comp.grafico.semDado': 'sem dado',

    // barra de cima
    'barra.holding': 'Holding',
    'barra.holding.nome': 'Nome',
    'barra.holding.padrao': 'Held',
    'barra.holding.nota': 'O valor da Holding soma o que ela tem e desconta a dívida.',
    'barra.marco.rotulo': 'Marco {n}: {nome}',
    'barra.marco.titulo': 'Marco {n} · {nome}',
    'barra.marco.xp': 'Pontos até o próximo marco',
    'barra.marco.deXp': '{xp} de {prox} XP',
    'barra.marco.faltam': 'Faltam {n} XP para o marco {prox}.',
    'barra.marco.ultimo': 'Último marco desta versão.',
    'barra.marco.requisito.torre.e4': 'Pede também a Torre Lâmina pronta.',
    'barra.creditos.rotulo': 'Créditos: {valor}; saldo {saldo}',
    'barra.pop.rotulo': 'População: {valor}; {hora}',
    'barra.pop.titulo': 'População',
    'barra.pop.moradores': 'Moradores',
    'barra.pop.ritmo': 'Novos moradores',
    'barra.bem.rotulo': 'Bem-estar {n}; {margem}',
    'barra.bem.rotuloVazia': 'Bem-estar; {margem}',
    'barra.bem.nome': 'Bem-estar',
    'barra.bem.titulo': 'Bem-estar {n}',
    'barra.bem.acima': '+{n} acima de {degrau}',
    'barra.bem.faltam': 'faltam {n} para {degrau}',
    'barra.bem.topo': 'faixa mais alta',
    'barra.bem.semMoradores': 'sem moradores',
    'barra.bem.paga': 'Cada morador contribui com {tarifa} créditos por hora de jogo.',
    'barra.bem.pagaVazia': 'Ainda sem moradores. A contribuição começa com os primeiros, pela faixa do bem-estar:',
    'barra.bem.cai': 'Abaixo de {degrau}, cai para {tarifa}.',
    'barra.bem.faixas': 'Faixas da contribuição',
    'barra.bem.ate': 'até {ate}',
    'barra.bem.deAte': '{de} a {ate}',
    'barra.bem.tarifa': '{tarifa}/h por morador',
    'barra.bem.media': 'Média dos prédios da cidade, suavizada em 1 mês e arredondada antes da faixa.',
    'barra.demanda.rotulo': 'Demanda: residencial {r}, comercial {c}, indústria {i}',
    'barra.demanda.titulo': 'Demanda',
    'barra.demanda.R': 'Residencial',
    'barra.demanda.C': 'Comercial',
    'barra.demanda.I': 'Indústria',
    'barra.demanda.E': 'Escritórios',
    'barra.demanda.nota': 'De 0 a 100: quanto a cidade quer de cada zona agora.',
    'barra.valuation': 'Valor da Holding',
    'barra.divida': 'Dívida',
    'barra.caixa': 'Caixa',
    'barra.tela.holding': 'Holding',
    'barra.tela.economia': 'Economia',
    'barra.tela.cidade': 'Cidade',
    'barra.tela.progresso': 'Progresso',
    'barra.tela.conselho': 'Conselho',
    'barra.ver.progresso': 'Ver marcos',
    'barra.ver.cidade': 'Ver a cidade',
    'barra.conselho': 'Conselho: decisões pendentes, {n}',
    'barra.conselho.pendentes': 'Decisões pendentes',
    'barra.menu': 'Menu',
    'barra.mesN': 'Mês {mes}',
    'barra.anoN': 'Ano {ano}',
    'barra.data.mes': 'Mês do ano',
    'barra.data.mesDe': '{mes} de 12',
    'barra.data.anoNovo': 'Ano {ano} começa em',
    'barra.data.escala': `Um mês do calendário dura ${MES / MINUTO} min de jogo; um ano, ${ANO / HORA} h.`,
    'barra.data.emprestimo': 'O ano rege o limite do empréstimo.',

    // cartão do selecionado
    'cartao.servico': 'Serviço',
    'cartao.servico.agua': 'Água',
    'cartao.servico.esgoto': 'Esgoto',
    'cartao.servico.energia': 'Energia',
    'cartao.servico.saude': 'Saúde',
    'cartao.servico.educacao': 'Educação',
    'cartao.servico.seguranca': 'Segurança',
    'cartao.servico.policia': 'Segurança',
    'cartao.servico.bombeiros': 'Bombeiros',
    'cartao.servico.lazer': 'Lazer',
    'cartao.servico.praca': 'Praça',
    'cartao.servico.parque': 'Parque',
    'cartao.sub.alcance': '{tipo} · alcance de {m} m',
    'cartao.sub.nivel': '{tipo} · nível {nivel} de 5',
    'cartao.holding': 'Prédio da Holding',
    'cartao.predio': 'Prédio',
    'cartao.moradores': 'Moradores',
    'cartao.bemEstar': 'Bem-estar',
    'cartao.contribuicao': 'Contribuição',
    'cartao.atendidos': 'Atendidos',
    'cartao.eficiencia': 'Eficiência',
    'cartao.manutencao': 'Manutenção',
    'cartao.trabalhadores': 'Trabalhadores',
    'cartao.produtividade': 'Produtividade',
    'cartao.nivel': 'Nível',
    'cartao.linhas': 'Linhas ativas',
    'cartao.deN': '{a} de {b}',
    'cartao.aviso.semAgua': 'Sem água',
    'cartao.aviso.semEsgoto': 'Sem esgoto',
    'cartao.aviso.semEnergia': 'Sem energia',
    'cartao.aviso.semAcesso': 'Sem acesso à rua',
    'cartao.aviso.abandonado': 'Abandonado',
    'cartao.aviso.semMaterial': 'Obra parada: falta material',
    'cartao.aviso.semTrabalhadores': 'Faltam trabalhadores',
    'cartao.aviso.racionado': 'Água ou energia racionada',
    'cartao.aviso.grave': 'Problema grave neste prédio',
    'cartao.aviso.atencao': 'Este prédio precisa de atenção',
    'cartao.aviso.info': 'Aviso sobre este prédio',
    'cartao.aviso.holding': 'Aviso da Holding',
    'cartao.desde': 'há {n} min de jogo',
    'cartao.obra': 'Em obra: {fase}',
    'cartao.obra.canteiro': 'canteiro',
    'cartao.obra.fundacao': 'fundação',
    'cartao.obra.estrutura': 'estrutura',
    'cartao.obra.fechamento': 'fechamento',
    'cartao.detalhes': 'Detalhes',

    // tela Economia
    'eco.titulo': 'Economia',
    'eco.aba.orcamento': 'Orçamento',
    'eco.aba.emprestimo': 'Empréstimo',
    'eco.semDados': 'Os números da economia aparecem quando a partida começa.',
    'eco.saldoHora': 'Saldo por hora',
    'eco.dicaHora': 'O que é hora de jogo',
    'eco.conta': 'Receitas {rec} e despesas {des}',
    'eco.caixa': 'Caixa',
    'eco.divida': 'Dívida',
    'eco.valuation': 'Valor da Holding',
    'eco.graficoCaixa': 'Caixa nos últimos 12 meses',
    'eco.graficoFluxo': 'Receitas e despesas por hora',
    'eco.receitasCurto': 'Receitas',
    'eco.despesasCurto': 'Despesas',
    'eco.mes': 'Mês {mes}',
    'eco.mil': '{n} mil',
    'eco.receitas': 'Receitas por hora',
    'eco.despesas': 'Despesas por hora',
    'eco.rec.moradores': 'Contribuição dos moradores',
    'eco.rec.cidade': 'Material vendido à cidade',
    'eco.rec.deposito': 'Vendas no Depósito',
    'eco.rec.marcos': 'Prêmios de marco',
    'eco.des.servicos': 'Manutenção dos serviços',
    'eco.des.vias': 'Manutenção das vias',
    'eco.des.ligacao': 'Energia de fora',
    'eco.des.salarios': 'Salários da Holding',
    'eco.des.juros': 'Juros do empréstimo',
    'eco.des.importacao': 'Material importado pela Holding',
    'eco.des.importacaoCidade': 'Importação para a cidade',
    'eco.regra': 'Contribuição: {pop} × {tarifa} = {total}/h',
    'eco.regraMedia': 'Média de {media} por morador: {total}/h',
    'eco.regraFaixa': 'Bem-estar {bem}: a faixa de {de} a {ate} paga {tarifa} por morador',
    'eco.naoPago': 'Sem pagar nesta hora',
    'eco.naoPago.servicos': 'Serviços',
    'eco.naoPago.servicos.efeito': 'trabalham só na fração paga',
    'eco.naoPago.salarios': 'Salários da Holding',
    'eco.naoPago.salarios.efeito': 'linhas da Holding e obras da Arcologia param',
    'eco.tudoPago': 'Tudo pago nesta hora.',
    'eco.caixaNunca': 'O caixa nunca fica abaixo de zero: o que não dá para pagar não vira dívida.',
    'eco.livia': 'Lívia Andrade, diretora financeira',
    'eco.livia.fala': 'As regras do empréstimo valem para a partida inteira. Use nos primeiros anos e quite cedo.',
    'eco.livia.ano': 'O limite deste ano acabou. No Ano {ano} ele volta inteiro.',
    'eco.regras': 'Regras do empréstimo',
    'eco.regra.porAno': 'Até {n} por ano do calendário',
    'eco.regra.taxa': 'Juros de {pct}% ao ano sobre o saldo de cada contrato',
    'eco.regra.divida': 'Dívida total até {n}, contando os juros devidos',
    'eco.regra.prazo': 'Prazo de {anos} anos; depois, juros de {mora}% ao ano',
    'eco.regra.passo': 'Tomado em múltiplos de {n}',
    'eco.disponivel': 'Disponível no Ano {ano}',
    'eco.deN': '{a} de {b}',
    'eco.tomar': 'Tomar empréstimo',
    'eco.valorTomar': 'Valor a tomar',
    'eco.tomarN': 'Tomar {n}',
    'eco.tomado': '{n} entrou no caixa.',
    'eco.bloqueio.ano': 'O limite deste ano acabou. Ele volta no Ano {ano}.',
    'eco.bloqueio.divida': 'A dívida chegou ao máximo permitido.',
    'eco.contratos': 'Contratos',
    'eco.col.ano': 'Ano',
    'eco.col.valor': 'Valor',
    'eco.col.saldo': 'Saldo',
    'eco.col.vence': 'Vence',
    'eco.col.juros': 'Juros',
    'eco.anoN': 'Ano {ano}',
    'eco.pagarJuros': 'Pagar juros ({n})',
    'eco.semJuros': 'Não há juros a pagar agora.',
    'eco.pagarParcela': 'Pagar parcela',
    'eco.parcelaDica': 'Juros mais 10% do principal, no mínimo 1.000, dos contratos mais antigos primeiro.',
    'eco.quitar': 'Quitar tudo ({n})',
    'eco.pago': 'Pagamento feito.',
    'eco.quitado': 'Dívida quitada.',
    'eco.semDivida': 'Sem dívida. O empréstimo fica à mão quando precisar.',
  });
}
