// Textos das telas do sistema da U2a (menu inicial, nova partida, saves, créditos, configurações e teste de
// desempenho), sob demanda: o corpo das telas registra ao chegar (inicio/corpo/comum.js). Português do Brasil, frases
// curtas, sem travessão, unidades da D42; o calendário é real (D67).
export function registrar(registrarTextos) {
  registrarTextos('u2', {
    'u2.menu.titulo': 'Menu inicial',
    'u2.menu.continuar': 'Continuar',
    'u2.menu.abrindo': 'Abrindo a partida...',
    'u2.menu.nova': 'Nova partida',
    'u2.menu.novaSub': 'A Holding Held chega a Heldópolis em jan. 2020',
    'u2.menu.carregar': 'Carregar',
    'u2.menu.config': 'Configurações',
    'u2.menu.creditos': 'Créditos',
    'u2.menu.versao': 'Versão {v}',
    'u2.menu.salvo': 'salvo {quando}',
    'u2.menu.rodape': 'Feito para o PC do dono',
    'u2.moradores': '{n} moradores',
    'u2.holdingSemNome': 'Holding',
    'u2.tempo.agora': 'agora há pouco',
    'u2.tempo.min': 'há {n} min',
    'u2.tempo.h': 'há {n} h',
    'u2.tempo.data': 'em {data}',
    'u2.sim': 'sim',
    'u2.nao': 'não',
    'u2.nova.titulo': 'Nova partida',
    'u2.nova.nome': 'Nome da Holding',
    'u2.nova.criador': 'Criador',
    'u2.nova.cor': 'Cor da marca',
    'u2.nova.mapa': 'Mapa: Heldópolis, na República de Vera Cruz do Leste. A sede, o Park of Future Dreams, fica no sul, de frente para o mar.',
    'u2.nova.calendario': 'A partida começa em {data}. 1 h de jogo em 1x são 6 meses do calendário.',
    'u2.nova.dicas': 'Dicas da primeira hora',
    'u2.nova.comecar': 'Começar',
    'u2.nova.comecando': 'Preparando Heldópolis...',
    'u2.nova.invalido.nome': 'Dê um nome à Holding, com até 32 letras.',
    'u2.nova.invalido.criador': 'Escreva o nome do criador, com até 40 letras.',
    'u2.cor.champanhe': 'Champanhe',
    'u2.cor.bronze': 'Bronze',
    'u2.cor.platina': 'Platina',
    'u2.cor.safira': 'Safira',
    'u2.cor.esmeralda': 'Esmeralda',
    'u2.cor.bordo': 'Bordô',
    'u2.cred.criador': 'Criado por Diogo Holanda',
    'u2.cred.criador.exp': 'Holding Held, Heldópolis e a Arcologia de Held',
    'u2.cred.cidade': 'Heldópolis',
    'u2.cred.cidade.exp': 'cidade fictícia na República de Vera Cruz do Leste; nomes de gente, empresa e país são fictícios',
    'u2.cred.motor': 'three.js',
    'u2.cred.motor.exp': 'licença MIT',
    'u2.cred.fonte': 'Inter',
    'u2.cred.fonte.exp': 'Rasmus Andersson, SIL Open Font License',
    'u2.cred.interface': 'Preact e Preact Signals',
    'u2.cred.interface.exp': 'licença MIT',
    'u2.cred.som': 'Som',
    'u2.cred.som.exp': 'todo gerado na hora pelo Web Audio, sem arquivos',
    'u2.slot.auto': 'Automático {n}',
    'u2.slot.manual': 'Espaço {n}',
    'u2.slot.quarentena': 'Cópia guardada',
    'u2.slot.vazio': 'vazio',
    'u2.sv.automaticos': 'Automáticos (a cada 5 min e ao sair)',
    'u2.sv.manuais': 'Seus espaços',
    'u2.sv.carregar': 'Carregar',
    'u2.sv.exportar': 'Exportar',
    'u2.sv.importar': 'Importar arquivo',
    'u2.sv.apagar': 'Apagar',
    'u2.sv.apagarArmado': 'Toque de novo para apagar',
    'u2.sv.salvarAqui': 'Salvar aqui',
    'u2.sv.substituir': 'Salvar por cima',
    'u2.sv.substituirArmado': 'Toque de novo para substituir',
    'u2.sv.nota': 'Arquivos .held de outro aparelho entram aqui.',
    'u2.sv.ocupado.carregar': 'Abrindo a partida...',
    'u2.sv.ocupado.exportar': 'Preparando o arquivo...',
    'u2.sv.ocupado.apagar': 'Apagando...',
    'u2.sv.ocupado.salvar': 'Salvando...',
    'u2.sv.ocupado.importar': 'Conferindo o arquivo...',
    'u2.sv.nenhum': 'Nenhuma partida salva ainda.',
    'u2.sv.semAutomatico': 'O primeiro automático sai quando a partida começa.',
    'u2.sv.semManual': 'Nenhum espaço usado.',
    'u2.sv.quarentena': 'Cópias danificadas',
    'u2.sv.quarentenaNota': 'Saves que não abriram ficam guardados aqui, nunca apagados. Exporte para mandar.',
    'u2.sv.semMotivo': 'sem detalhe',
    'u2.sv.exportado': 'Arquivo {nome} pronto.',
    'u2.sv.importado': 'Partida importada e aberta.',
    'u2.sv.naoImportou': 'O arquivo não entrou: {motivo}',
    'u2.sv.salvoEm': 'Salvo em {espaco}.',
    'u2.falha.nada': 'Não há save para isso.',
    'u2.falha.ocupado': 'Um save já está sendo gravado. Tente de novo em instantes.',
    'u2.falha.outraPagina': 'Outra aba está com esta partida.',
    'u2.falha.danificado': 'O save está danificado.',
    'u2.falha.valor': 'Este arquivo não é um save da Arcologia de Held.',
    'u2.falha.erro': 'Não foi possível concluir agora.',
    'u2.cfg.aba.video': 'Vídeo',
    'u2.cfg.aba.interface': 'Interface',
    'u2.cfg.aba.controles': 'Controles',
    'u2.cfg.aba.som': 'Som',
    'u2.cfg.aba.jogo': 'Jogo',
    'u2.cfg.aba.acessibilidade': 'Acessibilidade',
    'u2.cfg.aba.salvamento': 'Salvamento',
    'u2.cfg.aba.sobre': 'Sobre',
    'u2.cfg.teclasAbas': 'Page Up e Page Down (ou [ e ]) trocam a aba; Esc fecha.',
    'u2.cfg.qualidade': 'Qualidade',
    'u2.cfg.orcamento': 'até {calls} chamadas e {tris} triângulos',
    'u2.cfg.qAuto': 'Auto escolhe pela placa ({gpu}): {nome}, {orcamento}.',
    'u2.cfg.qExp.ultra': 'Ultra: {orcamento}, para placas maiores que a do dono.',
    'u2.cfg.qExp.alta': 'Alta: {orcamento}, para placas de jogo de hoje.',
    'u2.cfg.qExp.pc': 'PC: {orcamento}, 60 qps com piso de 30, em 1080p com resolução dinâmica. Feito para o PC do dono (RX 550).',
    'u2.cfg.qExp.media': 'Média: {orcamento}, para celulares como o Poco X7.',
    'u2.cfg.qExp.leve': 'Leve: {orcamento}, para aparelhos fracos.',
    'u2.cfg.semPlaca': 'placa sem nome',
    'u2.cfg.manter': 'Manter esta qualidade? Volta sozinha em {s} s.',
    'u2.cfg.manterSim': 'Manter',
    'u2.cfg.manterNao': 'Voltar',
    'u2.cfg.voltou': 'A qualidade voltou para {nome}.',
    'u2.cfg.dinamica': 'Resolução dinâmica',
    'u2.cfg.dinamicaExp': 'Baixa o desenho interno até 70% quando a placa passa de 15,5 ms por quadro e sobe de volta quando sobra.',
    'u2.cfg.resAgora': 'Agora: {w} x {h} ({pct}% da nativa), {modo}.',
    'u2.cfg.resSem': 'Sem medida do render ainda.',
    'u2.cfg.resPendente': 'Por enquanto o perfil decide sozinho; o ajuste à mão chega com o render.',
    'u2.cfg.resModo.cronometro': 'pelo cronômetro da placa',
    'u2.cfg.resModo.quadro': 'pelo tempo de quadro',
    'u2.cfg.resModo.fixa': 'travada',
    'u2.cfg.nitidez': 'Nitidez (CAS)',
    'u2.cfg.nitidezExp': 'Devolve o detalhe quando a imagem é ampliada. Força agora: {cas}.',
    'u2.cfg.nitidezAuto': 'Automática',
    'u2.cfg.nitidezNao': 'Desligada',
    'u2.cfg.sempreDia': 'Luz fixa de manhã',
    'u2.cfg.sempreDiaExp': 'O céu fica de manhã; o calendário segue andando.',
    'u2.cfg.painel': 'Painel de desempenho',
    'u2.cfg.painelExp': 'qps, ms, chamadas, triângulos, placa e memória num canto da tela. Atalho: F9.',
    'u2.cfg.teste': 'Teste de desempenho',
    'u2.cfg.testeExp': 'Voa 20 s pela sua cidade e mede. O resultado se copia para mandar.',
    'u2.cfg.testeNoInicio': 'Entre numa partida para medir a sua cidade.',
    'u2.cfg.testeAbrir': 'Abrir o teste',
    'u2.cfg.tamanho': 'Tamanho da interface',
    'u2.cfg.tamanhoExp': '90% só no PC.',
    'u2.cfg.pausarTelas': 'Pausar ao abrir telas',
    'u2.cfg.pausarTelasExp': 'Holding, Economia, Cidade e as outras pausam o tempo enquanto estão abertas. O menu sempre pausa.',
    'u2.cfg.cenasMarco': 'Cenas de marco',
    'u2.cfg.cenasMarcoExp': 'A câmera voa e o título aparece a cada marco e etapa da Arcologia.',
    'u2.cfg.cartaoNoPC': 'Cartão antes da folha',
    'u2.cfg.cartaoNoPCExp': 'No PC, tocar num prédio mostra o cartão curto antes da folha inteira.',
    'u2.cfg.avisos': 'Avisos sobre os prédios',
    'u2.cfg.avisosExp': 'Quais sinais aparecem no mundo. Com uma camada ligada, só os dela.',
    'u2.cfg.mira': 'Mira acima do dedo',
    'u2.cfg.miraExp': 'Quanto a mira das ferramentas fica acima do dedo, no toque.',
    'u2.cfg.borda': 'Rolar pela borda da tela',
    'u2.cfg.bordaExp': 'A câmera anda quando o mouse encosta na borda da janela.',
    'u2.cfg.teclas': 'Teclas',
    'u2.som.som': 'Geral',
    'u2.som.musica': 'Música',
    'u2.som.ambiente': 'Ambiente',
    'u2.som.efeitos': 'Efeitos do mundo',
    'u2.som.interface': 'Interface',
    'u2.som.fundo': 'Silenciar em segundo plano',
    'u2.som.fundoExp': 'O som para quando o jogo sai da frente.',
    'u2.som.vibrar': 'Vibração',
    'u2.som.vibrarExp': 'No encaixe, no confirmar, no erro e no marco. Só no Android.',
    'u2.cfg.autoSalvar': 'Salvamento automático',
    'u2.cfg.autoSalvarExp': 'A cada 5 min de relógio se algo mudou e ao sair, em 3 espaços que se revezam.',
    'u2.cfg.dicas': 'Dicas',
    'u2.cfg.dicasExp': 'Uma dica curta na primeira vez de cada coisa e os traçados sugeridos.',
    'u2.cfg.dicasDeNovo': 'Ver as dicas de novo',
    'u2.cfg.dicasDeNovoExp': 'As que já apareceram voltam uma vez.',
    'u2.cfg.dicasDeNovoBt': 'Mostrar de novo',
    'u2.cfg.dicasVoltam': 'As dicas voltam a aparecer.',
    'u2.cfg.calendario': 'Calendário',
    'u2.cfg.calendarioExp': 'A partida começa em {data}. 1 h de jogo em 1x são 6 meses; a hora do céu não aparece em número.',
    'u2.cfg.contraste': 'Alto contraste',
    'u2.cfg.contrasteExp': 'Vidro mais escuro e texto mais forte.',
    'u2.cfg.movimento': 'Reduzir movimento',
    'u2.cfg.movimentoExp': 'Sem pulsos, voos curtos e trocas diretas.',
    'u2.cfg.mov.sistema': 'Do sistema',
    'u2.cfg.mov.sim': 'Ligado',
    'u2.cfg.mov.nao': 'Desligado',
    'u2.cfg.daltonismo': 'Cores das camadas para daltonismo',
    'u2.cfg.daltonismoExp': 'Nas camadas, o vermelho vira laranja, mais fácil de separar do azul.',
    'u2.cfg.salvarAgora': 'Salvar agora',
    'u2.cfg.salvarAgoraExp': 'No espaço desta partida, ou no primeiro livre.',
    'u2.cfg.salvarBt': 'Salvar',
    'u2.cfg.saves': 'Partidas salvas',
    'u2.cfg.savesExp': 'Carregar, salvar num espaço, exportar e apagar.',
    'u2.cfg.savesBt': 'Abrir',
    'u2.cfg.exportar': 'Exportar a partida',
    'u2.cfg.exportarExp': 'Um arquivo .held com a partida de agora (salva na hora), para guardar ou levar a outro aparelho.',
    'u2.cfg.importar': 'Importar arquivo',
    'u2.cfg.importarExp': 'O arquivo é conferido inteiro antes de ocupar um espaço.',
    'u2.cfg.armazenamento': 'Armazenamento',
    'u2.cfg.persSim': 'persistente: o navegador não apaga o jogo',
    'u2.cfg.persNao': 'não persistente: o navegador pode apagar quando faltar espaço',
    'u2.cfg.persSem': 'o navegador não informa',
    'u2.cfg.usado': '{mb} MB usados',
    'u2.cfg.quarentena': '{n} cópias danificadas guardadas',
    'u2.cfg.recomecar': 'Recomeçar a partida',
    'u2.cfg.recomecarExp': 'Uma Heldópolis nova com a mesma Holding. A de agora fica salva.',
    'u2.cfg.recomecarBt': 'Recomeçar',
    'u2.cfg.recomecarArmado': 'Toque de novo para recomeçar',
    'u2.cfg.sobre.versao': 'Versão',
    'u2.cfg.sobre.perfil': 'Qualidade em uso',
    'u2.cfg.sobre.placa': 'Placa de vídeo',
    'u2.cfg.sobre.capacidades': 'Capacidades',
    'u2.cfg.sobre.licencas': 'Licenças',
    'u2.cfg.semVersao': 'em desenvolvimento',
    'u2.cfg.sugerido': 'sugerida: {nome}',
    'u2.cfg.capac': 'corte de profundidade {clip}; desenho múltiplo {multi}; cronômetro da placa {timer}',
    'u2.cfg.licencasExp': 'Inter (SIL OFL), three.js (MIT), Preact (MIT)',
    'u2.tecla.espaco': 'Espaço',
    'u2.tecla.espaco.def': 'pausa e volta',
    'u2.tecla.velocidades': '1, 2, 3',
    'u2.tecla.velocidades.def': 'velocidade 1x, 2x e 4x',
    'u2.tecla.mover': 'W A S D, setas',
    'u2.tecla.mover.def': 'mover a câmera',
    'u2.tecla.girar': 'Q E, R F, roda',
    'u2.tecla.girar.def': 'girar, inclinar e aproximar',
    'u2.tecla.categorias': 'V Z X G',
    'u2.tecla.categorias.def': 'Vias, Zonas, Serviços e Lazer',
    'u2.tecla.empresas': 'H M B',
    'u2.tecla.empresas.def': 'Empresas, Arcologia e Demolir',
    'u2.tecla.telas': 'Shift mais 1 a 6',
    'u2.tecla.telas.def': 'Holding, Economia, Cidade, Progresso e Conselho',
    'u2.tecla.construir': 'Enter',
    'u2.tecla.construir.def': 'construir o que está na prévia',
    'u2.tecla.desfazer': 'Ctrl mais Z',
    'u2.tecla.desfazer.def': 'desfazer na ferramenta',
    'u2.tecla.esc': 'Esc',
    'u2.tecla.esc.def': 'cancela, fecha ou abre o menu',
    'u2.tecla.f9': 'F9',
    'u2.tecla.f9.def': 'painel de desempenho',
    'u2.td.intro': 'A interface some, a câmera voa {s} s pela sua cidade e o render mede cada quadro. Depois, copie o resultado e mande.',
    'u2.td.rodar': 'Rodar teste ({s} s)',
    'u2.td.rodando': 'Medindo...',
    'u2.td.deNovo': 'Rodar de novo ({s} s)',
    'u2.td.vazio': 'Nenhum teste nesta sessão ainda.',
    'u2.td.falhou': 'O teste não terminou. Tente de novo.',
    'u2.td.aplicar': 'Usar a qualidade {nome}',
    'u2.td.aplicado': 'Qualidade trocada para {nome}.',
    'u2.td.copiar': 'Copiar resultado',
    'u2.td.copiado': 'Resultado copiado.',
    'u2.td.compartilhar': 'Compartilhar',
    'u2.td.selecione': 'Selecione e copie o texto abaixo.',
    'u2.td.grupo.perfil': 'Perfil e resolução',
    'u2.td.grupo.quadro': 'Quadro',
    'u2.td.grupo.placa': 'Placa por passe',
    'u2.td.grupo.carga': 'Programas e memória',
    'u2.td.perfil': 'qualidade em uso',
    'u2.td.sugerido': 'sugerida',
    'u2.td.motivo': 'motivo',
    'u2.td.interna': 'resolução interna',
    'u2.td.daNativa': 'da nativa',
    'u2.td.dinamica': 'resolução dinâmica',
    'u2.td.dinFixa': 'travada',
    'u2.td.dinCronometro': 'pelo cronômetro da placa, alvo de {ms} ms',
    'u2.td.dinQuadro': 'pelo tempo de quadro',
    'u2.td.nitidez': 'nitidez (CAS)',
    'u2.td.qps': 'qps',
    'u2.td.msMedio': 'ms médio',
    'u2.td.p95': 'p95',
    'u2.td.pior': 'pior quadro',
    'u2.td.chamadas': 'chamadas (pior)',
    'u2.td.triangulos': 'triângulos (pior)',
    'u2.td.sombra': 'sombra',
    'u2.td.orcamento': 'orçamento',
    'u2.td.longas': 'tarefas longas',
    'u2.td.gpuCerca': 'placa (cerca)',
    'u2.td.gpuCronometro': 'placa (cronômetro)',
    'u2.td.passes': 'por passe',
    'u2.td.semCronometro': 'sem o cronômetro da placa neste aparelho',
    'u2.td.aquecimento': 'aquecimento',
    'u2.td.aquecido': '{n} programas em {ms} ms',
    'u2.td.aquecendo': 'ainda aquecendo',
    'u2.td.depois': 'compilações depois de pronto',
    'u2.td.nenhuma': 'nenhuma',
    'u2.td.video': 'memória de vídeo',
    'u2.td.programas': 'programas',
    'u2.td.placa': 'placa',
  });
}
