// Textos da X2 (ferramentas de construção): barra de construção, bandeja, barra da ferramenta, cotas, chips de
// encaixe, zonas, colocar, demolir e Áreas. Português do Brasil, frases curtas, sem travessão; taxas só em "/h" de jogo
// (D42). Os motivos longos das recusas são os 'codigo.*' da F0; aqui ficam os curtos do botão e das cotas.

export function registrar(registrarTextos) {
  registrarTextos('x2', {
    // barra de construção (D24)
    'x2.grupo.cidade': 'Construir a cidade',
    'x2.grupo.holding': 'Construir a Holding',
    'x2.cat.vias': 'Vias',
    'x2.cat.zonas': 'Zonas',
    'x2.cat.servicos': 'Serviços',
    'x2.cat.lazer': 'Lazer',
    'x2.cat.empresas': 'Empresas',
    'x2.cat.arcologia': 'Arcologia',
    'x2.cat.demolir': 'Demolir',
    'x2.cat.aberta': '{nome}: fechar a bandeja',
    'x2.arcologia.etapa': 'Uma etapa pode começar',
    'x2.arcologia.progresso': 'Arcologia: {pct} do megaprojeto',
    'x2.trancado': 'Marco {n}',
    'x2.trancadoAviso': 'Abre no marco {n}: {nome}.',
    'x2.trancadoSemNome': 'Abre no marco {n}.',
    'x2.atalho': 'Atalho: {k}',

    // bandeja
    'x2.bandeja.rotulo': 'Itens de {nome}',
    'x2.bandeja.vazia': 'Nada para construir aqui ainda.',
    'x2.bandeja.porMetro': '{v}/m',
    'x2.bandeja.largura': '{n} m',
    'x2.bandeja.faltam': 'Faltam {n}',
    'x2.bandeja.gratis': 'Sem custo',
    'x2.bandeja.apagar': 'Apagar zona',
    'x2.bandeja.atende': 'atende {n}',
    'x2.bandeja.detalhe.custo': 'Custo',
    'x2.bandeja.detalhe.faltam': 'Faltam',
    'x2.bandeja.detalhe.manutencao': 'Manutenção',
    'x2.bandeja.detalhe.alcance': 'Alcance',
    'x2.bandeja.detalhe.marco': 'Libera no marco',
    'x2.bandeja.porKm': '{v} por km',
    'x2.bandeja.andares': '{a} a {b} andares',

    // barra da ferramenta (desenho da UI 8.5)
    'x2.ferramenta.via': 'Traçar via',
    'x2.ferramenta.zona': 'Zonear',
    'x2.ferramenta.colocar': 'Colocar',
    'x2.ferramenta.demolir': 'Demolir',
    'x2.ferramenta.areas': 'Áreas',
    'x2.cancelar': 'Cancelar',
    'x2.sair': 'Sair da ferramenta',
    'x2.desfazer': 'Desfazer',
    'x2.desfazerN': 'Desfazer, {n} na sessão',
    'x2.construir': 'Construir',
    'x2.melhorar': 'Melhorar',
    'x2.pronto': 'Pronto',
    'x2.demolir': 'Demolir',
    'x2.comprar': 'Comprar',
    'x2.girar': 'Girar',
    'x2.tipo': 'Tipo de via',
    'x2.modo': 'Forma do traçado',
    'x2.modo.reta': 'Reta',
    'x2.modo.curva': 'Curva',
    'x2.modo.grade': 'Grade',
    'x2.modo.melhorar': 'Melhorar',
    'x2.continua': 'Contínua',
    'x2.encaixe': 'Encaixe',
    'x2.estimado': 'estimado',
    'x2.manutencao': 'manutenção {v}',

    // via: dicas por fase (toque e mouse)
    'x2.via.dica.ocioso': 'Toque onde a via começa',
    'x2.via.dica.ociosoMouse': 'Clique onde a via começa',
    'x2.via.dica.mirandoA': 'Solte para marcar o começo',
    'x2.via.dica.aFixo': 'Toque ou arraste até o fim',
    'x2.via.dica.aFixoMouse': 'Clique onde a via termina',
    'x2.via.dica.mirandoB': 'Solte para ver a via',
    'x2.via.dica.previa': 'Arraste as alças para ajustar',
    'x2.via.dica.grade': 'Arraste o fundo para abrir as quadras',
    'x2.via.dica.melhorar': 'Toque nas vias que quer melhorar',
    'x2.via.total': '{m} m · {custo}',
    'x2.via.grade': '{n} ruas · {m} m · {custo}',
    'x2.via.melhorar': '{n} trechos · {m} m · {custo}',
    'x2.via.melhorar1': '1 trecho · {m} m · {custo}',
    'x2.via.melhorarNada': 'Nenhum trecho aceita este tipo',
    'x2.via.demolirPredios': 'demole {n} prédios',
    'x2.via.demolirPredio1': 'demole 1 prédio',

    // motivos curtos (botão e cotas)
    'x2.motivo.agua': 'Cruza água',
    'x2.motivo.vao': 'Vão longo demais',
    'x2.motivo.declive': 'Íngreme demais',
    'x2.motivo.declivePct': 'Declive de {p}%: máximo {max}%',
    'x2.motivo.angulo': 'Ângulo fechado',
    'x2.motivo.curto': 'Curto demais',
    'x2.motivo.raio': 'Curva fechada',
    'x2.motivo.ladrilho': 'Fora das áreas',
    'x2.motivo.gleba': 'Na gleba da Arcologia',
    'x2.motivo.colisao': 'Bate em outra obra',
    'x2.motivo.marco': 'Ainda trancado',
    'x2.motivo.creditos': 'Faltam {n}',
    'x2.motivo.acesso': 'Sem frente para via',
    'x2.motivo.recurso': 'Sem o recurso aqui',
    'x2.motivo.valor': 'Não aceita este tipo',
    'x2.motivo.nada': 'Já é deste tipo',
    'x2.motivo.arcologia': 'Parte da Arcologia',
    'x2.motivo.rodovia': 'Rodovia do mapa',
    'x2.motivo.inexistente': 'Não existe mais',
    'x2.motivo.outro': 'Não dá para construir aqui',

    // cotas no mundo
    'x2.cota': '{m} m · {custo}',

    // chips de encaixe (desenho da UI 9.2)
    'x2.enc.no': 'Emenda',
    'x2.enc.aresta': 'Cruzamento',
    'x2.enc.angulo': '{v}°',
    'x2.enc.prolongamento': 'Prolongamento',
    'x2.enc.quadra': 'Quadra',
    'x2.enc.passo': '{v}°',
    'x2.enc.comprimento': '{v} m',

    // zonas (desenho da UI 9.3)
    'x2.zona.forma': 'Forma do pincel',
    'x2.zona.preencher': 'Preencher',
    'x2.zona.pincel': 'Pincel',
    'x2.zona.retangulo': 'Retângulo',
    'x2.zona.apagar': 'Apagar',
    'x2.zona.tamanho': 'Tamanho do pincel',
    'x2.zona.P': 'P',
    'x2.zona.M': 'M',
    'x2.zona.G': 'G',
    'x2.zona.qual': 'Zona',
    'x2.zonaCurta.resBaixa': 'Res. baixa',
    'x2.zonaCurta.resMedia': 'Res. média',
    'x2.zonaCurta.resAlta': 'Res. alta',
    'x2.zonaCurta.comBaixa': 'Com. baixa',
    'x2.zonaCurta.comAlta': 'Com. alta',
    'x2.zonaCurta.escritorio': 'Escritórios',
    'x2.zonaCurta.industria': 'Indústria',
    'x2.zona.demanda': 'Demanda',
    'x2.zona.dica.preencher': 'Toque numa quadra para preencher',
    'x2.zona.dica.pincel': 'Arraste para pintar',
    'x2.zona.dica.retangulo': 'Arraste a diagonal do retângulo',
    'x2.zona.dica.apagar': 'Toque ou arraste para tirar a zona',
    'x2.zona.celulas': '{n} células',
    'x2.zona.celula1': '1 célula',
    'x2.zona.comPredio': '{n} com prédio',
    'x2.zona.efeito': 'bem-estar da cidade {v}',

    // colocar (desenho da UI 9.4)
    'x2.colocar.custo': '{custo}',
    'x2.colocar.alcance': 'alcance {m} m',
    'x2.colocar.dica': 'Arraste para escolher o lugar',

    // demolir
    'x2.demolir.dica': 'Toque no que quer demolir. Arraste para marcar vários.',
    'x2.demolir.marcados': '{n} marcados',
    'x2.demolir.marcado1': '1 marcado',
    'x2.demolir.perde': 'perde {mor} moradores e {emp} empregos',
    'x2.demolir.vias': '{n} trechos de via, {m} m',
    'x2.demolir.via1': '1 trecho de via, {m} m',
    'x2.demolir.volta': 'volta cerca de {v}',
    'x2.demolir.holding': 'Inclui prédio da Holding',

    // Áreas (D3, D55)
    'x2.areas.dica': 'Toque numa área vizinha para ver o preço',
    'x2.areas.titulo': 'Área {i}, {j}',
    'x2.areas.holding': 'Já é da Holding',
    'x2.areas.trancada': 'Precisa encostar numa área da Holding',
    'x2.areas.preco': '{preco}',
    'x2.areas.desconto': 'desconto de {pct} pela Influência',
    'x2.areas.comprada': 'Área comprada.',

    // avisos da sessão
    'x2.desfeito': 'Desfeito.',
    'x2.nadaDesfazer': 'Nada para desfazer nesta sessão.',
    'x2.lupa': 'Lupa do traçado',
    'x2.mira': 'Mira',
  });
}
